language: cpp
matrix:
    include:
        -   os: linux
            addons:
                apt:
                    sources:
                        -   ubuntu-toolchain-r-test
                    packages:
                        - g++-4.9
            env:
                - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
    - eval "$(MATRIX_EVAL)"
before_script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
script:
    - cd build && ./cwrapper-test
